import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import TopMenu from "@/components/TopMenu";
import {Container, Row, Col } from 'react-bootstrap';
import NavigationMenu from "@/components/NavigationMenu";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Container fluid>
            <Row>
                <TopMenu/>
            </Row>
            <Row className="border">
                <NavigationMenu/>
                <Col className="border" md={10}>
                    {children}
                </Col>
            </Row>
            {/*<div className="d-flex justify-content-center mt-3">*/}
            {/*    <Button variant="primary">Click Me</Button>*/}

            {/*</div>*/}
        </Container>
        </body>
        </html>
    );
}
